// This file is generated by Slice Machine. Update with care!

import GalleryGrid from './GalleryGrid';
import ImageSlice from './ImageSlice';
import Project from './Project';
import Socials from './Socials';

export {
	GalleryGrid,
	ImageSlice,
	Project,
	Socials,
};

export const components = {
	gallery_grid: GalleryGrid,
	image_slice: ImageSlice,
	project: Project,
	socials: Socials,
};
